export { default as LoginScreen } from './Login'
export { default as RegisterScreen } from './Register'
export { default as HomeScreen } from './Home'
export { default as ParkingSpotScreen } from './ParkingSpot'
export { default as FindParkScreen } from './FindPark'
export { default as FindCarScreen } from './FindCar'
export { default as RegisterParkScreen } from './Parking'